# Generated by Django 4.1.4 on 2022-12-16 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('url', models.TextField(max_length=400)),
                ('stock', models.IntegerField()),
                ('prix', models.IntegerField()),
            ],
        ),
    ]
